name: Run Google Calendar Sync

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Decode credentials.json
      run: echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" | base64 -d > credentials.json

    - name: Decode token.json
      run: echo "${{ secrets.GOOGLE_TOKEN_JSON }}" | base64 -d > token.json

    - name: Run Python script
      run: python main.py
